## To add a coin, uncomment it by removing the # before the it.
## To remove a coin, just comment it out by adding # before it.  

coins_list = [

	"bitcoin",
	"ethereum",
#	"cardano",
	"binancecoin",
	"dogecoin",
	"stellar",
#	"artex",
	"bnbpay",
	"shiba-inu",
#	"hamster",
#	"tether",
#	"ripple",
	"solana",
#	"usd-coin",
#	"polkadot",
#	"terra-luna",
#	"avalanche-2",
#	"uniswap",
#	"binance-usd",
#	"chainlink",
#	"algorand",
#	"litecoin",
#	"bitcoin-cash",
#	"wrapped-bitcoin",
#	"cosmos",
#	"internet-computer",
#	"matic-network",
#	"filecoin",
#	"axie-infinity",
#	"vechain",
#	"ethereum-classic",
#	"ftx-token",
#	"tron",
#	"theta-token",
#	"tezos",
#	"dai",
#	"compound-ether",
#	"monero",
#	"elrond-erd-2",
#	"staked-ether",
#	"Lido Staked Ether",
#	"okb",
#	"eos",
	"pancakeswap-token",
#	"crypto-com-chain",
#	"ecash",
#	"hedera-hashgraph",
#	"aave",
#	"quant-network",
#	"bitcoin-cash-abc-2",
#	"near",
#	"the-graph",
#	"klay-token",
#	"fantom",
#	"iota",
#	"neo",
#	"kusama",
#	"bitcoin-cash-sv",
#	"leo-token",
#	"waves",
#	"compound-usd-coin",
#	"terrausd",
#	"amp-token",
#	"cdai",
#	"bittorrent-2",
#	"celsius-degree-token",
#	"arweave",
#	"thorchain",
#	"maker",
#	"olympus",
#	"helium",
#	"sushi",
#	"omisego",
#	"huobi-btc",
#	"celo",
#	"dash",
#	"compound-governance-token",
#	"harmony",
#	"havven",
#	"holotoken",
#	"xdce-crowd-sale",
#	"decred",
#	"theta-fuel",
#	"chiliz",
#	"enjincoin",
#	"nem",
#	"icon",
#	"blockstack",
#	"ecomi",
#	"zcash",
#	"bitclout",
#	"qtum",
#	"true-usd",
#	"flow",
#	"huobi-token",
#	"zilliqa",
#	"iostoken",
#	"mina-protocol",
#	"dydx",
#	"yearn-finance",
#	"curve-dao-token",
#	"serum",
#	"ravencoin",
#	"basic-attention-token",
	"cryptomines-eternal"

	]
